- hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  collections:
    - community.kubernetes

  tasks:
    - name: Ensure the myapp Namespace exists.
      k8s:
        api_version: v1
        kind: Namespace
        name: myapp
        state: absent
